-- Esquema canónico de clientes usado por los modelos TypeScript.
CREATE TABLE IF NOT EXISTS clientes (
  id CHAR(36) NOT NULL PRIMARY KEY,
  ruc_cedula VARCHAR(13) NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  responsible VARCHAR(150) NOT NULL,
  email VARCHAR(180) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  tax_regime VARCHAR(100) NOT NULL DEFAULT 'General regime',
  accounting_required ENUM('Yes', 'No') NOT NULL DEFAULT 'Yes',
  disabled_at TIMESTAMP NULL DEFAULT NULL,
  disabled_by BIGINT NULL DEFAULT NULL,
  COD_USUEMP BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UQ_CLIENTES_RUC_USUARIO (ruc_cedula, COD_USUEMP),
  KEY IDX_CLIENTES_USUARIO (COD_USUEMP),
  CONSTRAINT FK_CLIENTES_USUARIO FOREIGN KEY (COD_USUEMP)
    REFERENCES usuarios (COD_USUEMP) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
