CREATE TABLE IF NOT EXISTS estados_financieros_resumen (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  period_id BIGINT UNSIGNED NOT NULL,
  balance_document_id BIGINT UNSIGNED NULL,
  results_document_id BIGINT UNSIGNED NULL,
  activo_corriente DECIMAL(14,2) NULL,
  activo_no_corriente DECIMAL(14,2) NULL,
  total_activos DECIMAL(14,2) NULL,
  pasivo_corriente DECIMAL(14,2) NULL,
  pasivo_no_corriente DECIMAL(14,2) NULL,
  total_pasivos DECIMAL(14,2) NULL,
  patrimonio DECIMAL(14,2) NULL,
  ingresos_periodo DECIMAL(14,2) NULL,
  costos_gastos_operativos DECIMAL(14,2) NULL,
  utilidad_antes_participacion_impuestos DECIMAL(14,2) NULL,
  extraction_status ENUM('Pending','Completed','Error') NOT NULL DEFAULT 'Pending',
  extraction_error TEXT NULL,
  extracted_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_estados_financieros_periodo (period_id),
  KEY idx_estados_financieros_balance_document (balance_document_id),
  KEY idx_estados_financieros_results_document (results_document_id),
  CONSTRAINT fk_estados_financieros_periodo FOREIGN KEY (period_id) REFERENCES accounting_periods(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_estados_financieros_balance_documento FOREIGN KEY (balance_document_id) REFERENCES documentos_contables(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_estados_financieros_results_documento FOREIGN KEY (results_document_id) REFERENCES documentos_contables(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
