// src/config/retentionLabels.ts
export const RETENTION_LABELS: Record<string, string> = {
  '302': 'En relación de dependencia que supera o no la base desgravada',
  '303': 'Honorarios profesionales',
  '3030': 'Servicios profesionales prestados por sociedades residentes',
  '304': 'Predomina el intelecto',
  '307': 'Predomina la mano de obra',
  '308': 'Utilización o aprovechamiento de la imagen o renombre',
  '309': 'Publicidad y comunicación',
  '310': 'Transporte privado de pasajeros o servicio público o privado de carga',
  '311': 'A través de liquidaciones de compra (nivel cultural o rusticidad)',
  '312': 'Transferencia de bienes muebles de naturaleza corporal',
  '322': 'Seguros y reaseguros (primas y cesiones)',
  '3120': 'Compras al productor (bienes de origen agrícola, avícola, pecuario...)',
  '3121': 'Compras al comercializador (bienes de origen agrícola, avícola, pecuario...)',
  '3430': 'Actividades de construcción de obra material inmueble, urbanización, lotización',
  '343': 'Pagos aplicables el 1% (Energía Eléctrica y régimen RIMPE - Emprendedores)',
  '344': 'Pagos aplicables el 2% (tarjeta de crédito/débito, minerales, botellas PET)',
  '332': 'Pagos de bienes y servicios no sujetos a retención o con 0%',
  '314': 'Por regalías, derechos de autor, marcas, patentes y similares',
  '3140': 'Comisiones pagadas a sociedades residentes en el Ecuador',
  '319': 'Arrendamiento mercantil',
  '320': 'Arrendamiento de bienes inmuebles',
  '323': 'Rendimientos financieros',
  '324': 'Rendimientos financieros entre instituciones del sistema financiero',
  '3230': 'Otros rendimientos financieros 0%',
  '325': 'Anticipo dividendos',
  '3250': 'Dividendos exentos (no supera la franja exenta o beneficio de otras leyes)',
  '326': 'Dividendos distribuidos correspondientes al impuesto a la renta único (art. 27 LRTI)',
  '327': 'Dividendos distribuidos a personas naturales residentes',
  '328': 'Dividendos distribuidos a sociedades residentes',
  '329': 'Dividendos distribuidos a fideicomisos residentes',
  '330': 'Dividendos gravados distribuidos en acciones (reinversión de utilidades)',
  '331': 'Dividendos en acciones (capitalización de utilidades)',
  '333': 'Ganancia en enajenación de derechos representativos de capital (cotizados)',
  '334': 'Contraprestación en enajenación de derechos representativos de capital (no cotizados)',
  '335': 'Loterías, rifas, apuestas, pronósticos deportivos y similares',
  '3482': 'Autorretenciones Sociedades Grandes Contribuyentes (% de autorretención)',
  '336': 'Venta de combustibles a comercializadoras',
  '337': 'Venta de combustibles a distribuidores',
  '3370': 'Retención a cargo del propio sujeto pasivo (productos forestales)',
  '350': 'Otras autorretenciones (inciso 1 y 2 Art.92.1 RLRTI)',
  '3440': 'Otras retenciones aplicables el 2,75%',
  '345': 'Otras retenciones aplicables el 8%',
  '346': 'Otras retenciones aplicables a otros porcentajes (donaciones en dinero)',
  '349': 'SUBTOTAL OPERACIONES EFECTUADAS EN EL PAÍS',
  '402': 'Intereses por financiamiento de proveedores (con convenio doble tributación)',
  '403': 'Intereses de créditos (con convenio)',
  '404': 'Anticipo de dividendos (con convenio)',
  '405': 'Dividendos distribuidos a personas naturales (con convenio)',
  '406': 'Dividendos distribuidos a sociedades (con convenio)',
  '407': 'Dividendos distribuidos a fideicomisos (con convenio)',
  '4050': 'Dividendos sin beneficiario efectivo persona natural residente (con convenio)',
  '4060': 'Dividendos con beneficiario efectivo persona natural residente (con convenio)',
  '4070': 'Dividendos incumpliendo deber de informar composición societaria (con convenio)',
  '408': 'Pago a no residentes - Enajenación derechos representativos capital (con convenio)',
  '409': 'Seguros y reaseguros (con convenio)',
  '410': 'Servicios técnicos, administrativos, consultoría y regalías (con convenio)',
  '411': 'Otros conceptos de ingresos gravados (con convenio)',
  '412': 'Otros pagos al exterior no sujetos a retención (con convenio)',
  '413': 'Intereses por financiamiento de proveedores (sin convenio)',
  '414': 'Intereses de créditos (sin convenio)',
  '415': 'Anticipo de dividendos (sin convenio)',
  '416': 'Dividendos distribuidos a personas naturales (sin convenio)',
  '417': 'Dividendos distribuidos a sociedades (sin convenio)',
  '418': 'Dividendos distribuidos a fideicomisos (sin convenio)',
  '4160': 'Dividendos sin beneficiario efectivo (sin convenio)',
  '4170': 'Dividendos con beneficiario efectivo (sin convenio)',
  '4180': 'Dividendos incumpliendo deber de informar (sin convenio)',
  '419': 'Pago a no residentes - Enajenación derechos representativos capital (sin convenio)',
  '420': 'Seguros y reaseguros (sin convenio)',
  '421': 'Servicios técnicos, administrativos, consultoría y regalías (sin convenio)',
  '422': 'Otros conceptos de ingresos gravados (sin convenio)',
  '423': 'Otros pagos al exterior no sujetos a retención (sin convenio)',
  '424': 'Intereses (paraísos fiscales)',
  '425': 'Anticipo de dividendos (paraísos fiscales)',
  '426': 'Dividendos distribuidos a personas naturales (paraísos fiscales)',
  '427': 'Dividendos distribuidos a sociedades (paraísos fiscales)',
  '428': 'Dividendos distribuidos a fideicomisos (paraísos fiscales)',
  '4260': 'Dividendos sin beneficiario efectivo (paraísos fiscales)',
  '4270': 'Dividendos con beneficiario efectivo (paraísos fiscales)',
  '4280': 'Dividendos incumpliendo deber de informar (paraísos fiscales)',
  '429': 'Pago a no residentes - Enajenación derechos representativos capital (paraísos fiscales)',
  '430': 'Seguros y reaseguros (paraísos fiscales)',
  '431': 'Servicios técnicos, administrativos, consultoría y regalías (paraísos fiscales)',
  '432': 'Otros conceptos de ingresos gravados (paraísos fiscales)',
  '433': 'Otros pagos al exterior no sujetos a retención (paraísos fiscales)',
  '497': 'SUBTOTAL OPERACIONES EFECTUADAS CON EL EXTERIOR',
  '499': 'TOTAL DE RETENCIÓN DE IMPUESTO A LA RENTA',
  '500': 'Compensación de pago a cuenta por utilidades no distribuidas',
  '501': 'TOTAL DE RETENCIÓN DE IMPUESTO A LA RENTA DESPUÉS DE COMPENSACIÓN',
  '890': 'Pago previo',
  '897': 'Interés',
  '898': 'Impuesto',
  '899': 'Multa',
  '880': 'Pago directo en cuenta única del tesoro nacional',
  '902': 'TOTAL IMPUESTO A PAGAR',
  '903': 'Interés por mora',
  '904': 'Multa',
  '999': 'TOTAL PAGADO',
};
export const RETENTION_FIELD_PAIRS: Array<{ base: string; retained?: string; extra?: string[] }> = [
  { base: '302', retained: '352' },
  { base: '303', retained: '353' },
  { base: '3030', retained: '3530' },
  { base: '304', retained: '354' },
  { base: '307', retained: '357' },
  { base: '308', retained: '358' },
  { base: '309', retained: '359' },
  { base: '310', retained: '360' },
  { base: '311', retained: '361' },
  { base: '312', retained: '362' },
  { base: '322', retained: '372' },
  { base: '3120', retained: '3620' },
  { base: '3121', retained: '3621' },
  { base: '3430', retained: '3450' },
  { base: '343', retained: '393' },
  { base: '344', retained: '394' },
  { base: '332' },
  { base: '314', retained: '364' },
  { base: '3140', retained: '3640' },
  { base: '319', retained: '369' },
  { base: '320', retained: '370' },
  { base: '323', retained: '373' },
  { base: '324', retained: '374' },
  { base: '3230' },
  { base: '325', retained: '375' },
  { base: '3250' },
  { base: '326', retained: '376' },
  { base: '327', retained: '377' },
  { base: '328', retained: '378' },
  { base: '329', retained: '379' },
  { base: '330', retained: '380' },
  { base: '331' },
  { base: '333', retained: '383' },
  { base: '334', retained: '384' },
  { base: '335', retained: '385' },
  { base: '3482', extra: ['3481', '3981'] },
  { base: '336', retained: '386' },
  { base: '337', retained: '387' },
  { base: '3370', retained: '3870' },
  { base: '350', retained: '400' },
  { base: '3440', retained: '3940' },
  { base: '345', retained: '395' },
  { base: '346', retained: '396' },
  { base: '349', retained: '399' },
  { base: '402', retained: '452' }, { base: '403', retained: '453' }, { base: '404', retained: '454' },
  { base: '405' }, { base: '406', retained: '456' }, { base: '407', retained: '457' },
  { base: '4050', retained: '4550' }, { base: '4060', retained: '4560' }, { base: '4070', retained: '4570' },
  { base: '408', retained: '458' }, { base: '409', retained: '459' }, { base: '410', retained: '460' },
  { base: '411', retained: '461' }, { base: '412' },
  { base: '413', retained: '463' }, { base: '414', retained: '464' }, { base: '415', retained: '465' },
  { base: '416' }, { base: '417', retained: '467' }, { base: '418', retained: '468' },
  { base: '4160', retained: '4660' }, { base: '4170', retained: '4670' }, { base: '4180', retained: '4680' },
  { base: '419', retained: '469' }, { base: '420', retained: '470' }, { base: '421', retained: '471' },
  { base: '422', retained: '472' }, { base: '423' },
  { base: '424', retained: '474' }, { base: '425', retained: '475' }, { base: '426', retained: '476' },
  { base: '427', retained: '477' }, { base: '428', retained: '478' },
  { base: '4260', retained: '4760' }, { base: '4270', retained: '4770' }, { base: '4280', retained: '4780' },
  { base: '429', retained: '479' }, { base: '430', retained: '480' }, { base: '431', retained: '481' },
  { base: '432', retained: '482' }, { base: '433' },
  { base: '497', retained: '498' },
  { base: '499' }, { base: '500' }, { base: '501' },
  { base: '890' }, { base: '897' }, { base: '898' }, { base: '899' }, { base: '880' },
  { base: '902' }, { base: '903' }, { base: '904' }, { base: '999' },
];